.ALIASES
R_R1            R1(1=N00106 2=N00113 ) CN @TEST.SCHEMATIC1(sch_1):INS40@ANALOG.R.Normal(chips)
V_V1            V1(+=N00106 -=0 ) CN @TEST.SCHEMATIC1(sch_1):INS65@SOURCE.VDC.Normal(chips)
D_D1            D1(A=0 K=N00113 ) CN @TEST.SCHEMATIC1(sch_1):INS90@DIODE.1N5225.Normal(chips)
V_V2            V2(+=N00293 -=0 ) CN @TEST.SCHEMATIC1(sch_1):INS197@SOURCE.VAC.Normal(chips)
R_R2            R2(1=N00293 2=OUT ) CN @TEST.SCHEMATIC1(sch_1):INS226@ANALOG.R.Normal(chips)
R_R3            R3(1=0 2=OUT ) CN @TEST.SCHEMATIC1(sch_1):INS252@ANALOG.R.Normal(chips)
C_C1            C1(1=0 2=OUT ) CN @TEST.SCHEMATIC1(sch_1):INS277@ANALOG.C.Normal(chips)
_    _(OUT=OUT)
.ENDALIASES
